### ISSUE TITLE
Clickable routes and open in new tab

### ISSUE THREAD

**Issue by pravosudova** [tamiat/tamiat#158]
When a user create a route, usually he want to test it, a fast way of doing so would be clicking on the path, when the user click on the path it should open in a new tab.

**Comment by Abdelaziz18003** [comment]
opening the "dynamic path" in a new tab is impossible, because these routes are stored on firebase and not shipped into the app. so when openning a new tab with a dynamic route the "dynamic route" will not be found because it takes some time to be loaded from firebase. But we can open it in the same tab.

**Comment by pravosudova** [comment]
http://prntscr.com/j1e04y  mean about this. Those are routes which we create manually, but they are stored in the db. 
Do you still think its impossible?

**Comment by Abdelaziz18003** [comment]
Hi @pravosudova, we found a solution for opening dynamic routes in new tabs .. @nikkanetiya gave me the key to solve that problem .. many thanks to him
