### ISSUE TITLE
Adjust admin page design

### ISSUE THREAD

**Issue by mahnouman** [tamiat/tamiat#187]
Applying the new design to the admin pages.

**Comment by Abdelaziz18003** [comment]
after pulling the latest changes .. I saw that the admin is broken when resizing the browser

![screenshot-2018-5-13 tamiat cms front end focused cms based on vue js and firebase](https://user-images.githubusercontent.com/11301627/39968064-d37961de-56be-11e8-8624-f8f9edfcfef8.png)

**Comment by nikkanetiya** [comment]
Yes, I found the same. I think it is not responsive yet or has bug for smaller size screen especially for header.

**Comment by mohamedAdel01** [comment]
i will fix that now, i didn't make it responsive

**Comment by nikkanetiya** [comment]
@mohamedAdel01 Open any page directly except localhost:8080/admin for example `http://localhost:8080/admin/media` it will not show the logo, instead of this it will show the placeholder because logo image will not be found on that path, So that's why I have changed path static/logo-path to /static/logo-path. Please check the same.

![taimat_admin_nav](https://user-images.githubusercontent.com/6582898/39990950-9ab32722-578b-11e8-8f60-22f236e29d15.png)

**Comment by nikkanetiya** [comment]
one more minor issue with side nav-bar which has sub-items like contents. On hover the side will be closed something strange. Please just check it and if needed I will send you the video.

Thanks

**Comment by nikkanetiya** [comment]
And check another small issue for height
![taimat_admin_nav](https://user-images.githubusercontent.com/6582898/39991450-39ade550-578d-11e8-8c70-5c5960b6fecb.png)

**Comment by coderpradp** [comment]
@mahnouman Cross checked everything mentioned in this thread and it all seems to be as expected now. Safe to close it.
